- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
- id: clippy
  name: clippy
  description: lint files with cargo clippy
  entry: cargo clippy
  language: system
  types: [rust]
  args: []
